package:
  name: amazon-vpc-cni-k8s
  version: 1.18.0
  epoch: 0
  description: Networking plugin repository for pod networking in Kubernetes using Elastic Network Interfaces on AWS
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - cilium-iptables # This package contains the iptables-wrapper script: https://github.com/aws/amazon-vpc-cni-k8s/blob/b46e7038bff87059a3f182562447478f21177613/scripts/dockerfiles/Dockerfile.release#L27
      - iptables

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - cilium-iptables
      - dpkg
      - go
      - iptables

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/amazon-vpc-cni-k8s
      tag: v${{package.version}}
      expected-commit: b46e7038bff87059a3f182562447478f21177613

  - runs: |
      go version | awk '{print $3}' | sed 's/go//' > .go-version
      make build-aws-vpc-cni && make build-linux
      mkdir -p "${{targets.contextdir}}"/app
      install -m 755 -D ./misc/10-aws.conflist "${{targets.contextdir}}"/app/10-aws.conflist
      for binary in aws-cni aws-k8s-agent grpc-health-probe egress-cni aws-vpc-cni; do
          install -m 755 -D ./$binary "${{targets.contextdir}}"/app/$binary
      done

  - runs: |
      mkdir -p "${{targets.contextdir}}"/usr/sbin
      mkdir -p "${{targets.contextdir}}"/sbin
      ln -sf /sbin/iptables "${{targets.contextdir}}"/usr/sbin/iptables
      update-alternatives --install "${{targets.contextdir}}"/usr/sbin/iptables iptables /sbin/iptables-wrapper 100
      update-alternatives --set iptables /sbin/iptables-wrapper

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/amazon-vpc-cni-k8s
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set +e
        # same issue persists in the upstream container, see:
        # $ docker container run --rm public.ecr.aws/eks/amazon-k8s-cni:v1.18.0-eksbuild.1
        /app/aws-vpc-cni | grep "Failed to install CNI binaries"
