package:
  name: amazon-vpc-cni-k8s
  version: 1.18.0
  epoch: 0
  description: Networking plugin repository for pod networking in Kubernetes using Elastic Network Interfaces on AWS
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - cilium-iptables
      - go
      - iptables

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/amazon-vpc-cni-k8s
      tag: v${{package.version}}
      expected-commit: b46e7038bff87059a3f182562447478f21177613

  - runs: |
      go version | awk '{print $3}' | sed 's/go//' > .go-version
      make build-aws-vpc-cni && make build-linux
      mkdir -p "${{targets.contextdir}}"/app
      install -m 755 -D ./misc/10-aws.conflist "${{targets.contextdir}}"/app/10-aws.conflist
      for binary in aws-cni aws-k8s-agent grpc-health-probe egress-cni aws-vpc-cni; do
          install -m 755 -D ./$binary "${{targets.contextdir}}"/app/$binary
      done

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    # https://github.com/aws/amazon-vpc-cni-k8s/blob/389f5ebd62fda05776e837ad9a2dad5a8aec02cd/scripts/dockerfiles/Dockerfile.release#L27
    description: "This manually sets the symlink so that calls to iptables use the iptables-wrapper"
    dependencies:
      runtime:
        # https://github.com/wolfi-dev/os/blob/388b536baaf146b259bd57909e854ab403a07732/cilium-1.15.yaml#L169-L183
        # https://github.com/aws/amazon-vpc-cni-k8s/blob/389f5ebd62fda05776e837ad9a2dad5a8aec02cd/scripts/dockerfiles/Dockerfile.release#L27
        - cilium-iptables # it contains the iptables-wrapper script
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/sbin
          ln -s /usr/sbin/iptables-wrapper "${{targets.contextdir}}"/sbin/iptables

update:
  enabled: true
  github:
    identifier: aws/amazon-vpc-cni-k8s
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        # - busybox
        # - ca-certificates-bundle
        - iptables
        - cilium-iptables
  pipeline:
    - runs: |
        set +e
        # same issue persists in the upstream container, see:
        # $ docker container run --rm public.ecr.aws/eks/amazon-k8s-cni:v1.18.0-eksbuild.1
        /app/aws-vpc-cni | grep "Failed to install CNI binaries"
