#nolint:git-checkout-must-use-github-updates
package:
  name: confluent-kafka
  # Upstream versioning is too weird that we need to work-around it.
  # Release Monitor returns the latest version as `7.7.0-314-ccs` format:
  # https://release-monitoring.org/api/v2/versions/?project_id=371656
  # In order to make the `update:` section happy:
  # 1. We need to transform it by replacing the last `-` with `.` to match
  # with the `version:` field.
  # 2. Created a new variable `mangled-package-version` to append `-ccs` to the
  # version.
  version: 7.7.0.309
  epoch: 0
  description: Community edition of Confluent Kafka.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - zookeeper
      - bash # Requied by this images - uses shell to launch image wth zookeeper.

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - gradle
      - openjdk-11
      - sbt

var-transforms:
  - from: ${{package.version}}
    match: '\.(\d+)$'
    replace: '-$1-ccs'
    to: mangled-package-version

pipeline:
  - uses: fetch
    with:
      expected-sha256: 822400e2968973c648604fa89e40fef94c1076275dae4855df06c51c9b253f9f
      uri: https://github.com/confluentinc/kafka/archive/refs/tags/v${{vars.mangled-package-version}}.tar.gz

  - runs: |
      export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8

      gradle clean releaseTarGz

      nohup /usr/lib/kafka/bin/zookeeper-server-start.sh /usr/lib/kafka/config/zookeeper.properties > ${{targets.destdir}}/usr/lib/kafka/logs/zookeeper.out 2> zookeeper.err < /dev/null &
      tar -xzvf core/build/distributions/kafka_*-${{vars.mangled-package-version}}.tgz

      mkdir -p ${{targets.destdir}}/usr/lib/kafka/logs
      mkdir -p ${{targets.destdir}}/etc/kafka
      mkdir -p ${{targets.destdir}}/var/lib/kafka/data

      mv kafka_*-${{vars.mangled-package-version}}/bin ${{targets.destdir}}/usr/lib/kafka
      mv kafka_*-${{vars.mangled-package-version}}/libs ${{targets.destdir}}/usr/lib/kafka
      mv kafka_*-${{vars.mangled-package-version}}/config ${{targets.destdir}}/usr/lib/kafka

      # Install required runtime scripts
      mkdir -p ${{targets.destdir}}/usr/bin
      for file in $(find ./bin -type f -exec grep -lE '^#!(/usr/bin/env |/bin/)' {} \;); do
        filename=$(basename "$f")
        install -D -m755 "$file" ${{targets.destdir}}/usr/bin/"$filename"
      done

      # Create a symlink for the kafka libs since upstream images expect it to be in /usr/share/java/kafka:
      # https://github.com/confluentinc/kafka/blob/b66558da5d6b33c2fba9f424131575b948e6f611/bin/kafka-run-class.sh#L197
      mkdir -p ${{targets.destdir}}/usr/share/java/kafka
      ln -sf ${{targets.destdir}}/usr/lib/kafka/libs ${{targets.destdir}}/usr/share/java/kafka

      # Clean up windows
      rm -rf ${{targets.destdir}}/usr/lib/kafka/bin/*.bat

update:
  enabled: true
  release-monitor:
    identifier: 371645
  version-transform:
    - match: ^(.+)\-(\d+)$
      replace: $1.$2

test:
  environment:
    contents:
      packages:
        - zookeeper
        - busybox
        - netcat-openbsd
        - confluent-common-docker
        - confluent-common-docker-ub
        - confluent-common-docker-base
        - confluent-docker-utils
        - confluent-kafka-images-kafka
  pipeline:
    - runs: |
        export COMPONENT="kafka" KAFKA_ZOOKEEPER_CONNECT="127.0.0.1:2888" KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://localhost:9092" CLUSTER_ID="" CUB_CLASSPATH="/usr/share/java/kafka/*:/usr/share/java/cp-base-new/*:/usr/share/java/zookeeper/*:/usr/share/java/confluent-common-docker/*"
        set +e
        echo "Starting entrypoint..."
        logs=$(timeout -s KILL 10 /etc/confluent/docker/run 2>&1)
        set -e

        # Use assert_true for conditions that should be true
        assert_true() {
            local assert="$1"
            if ! echo "$logs" | grep -q "$assert"; then
                echo "Did not find '$assert' in logs"
                echo "$logs"
                exit 1
            fi
        }

        # Use assert_false for conditions that should be false
        assert_false() {
            local assert="$1"
            if echo "$logs" | grep -q "$assert"; then
                echo "Found '$assert' in logs"
                echo "$logs"
                exit 1
            fi
        }

        assert_true "Configuring"
        assert_true "Running preflight checks"
        # We couldn't run zookeeper in the CI for some reason so
        # package keep trying to connect to it as an expected case.
        # More detailed tests in the image.
        assert_true "Check if Zookeeper is healthy"

        # Ensure all required Java libs are available in the classpath
        assert_false "Could not find or load main class"
        assert_false "java.lang.ClassNotFoundException"
    - runs: |
        KAFKA_DIR=/usr/lib/kafka

        echo "Starting Zookeeper..."
        nohup "${KAFKA_DIR}/bin/zookeeper-server-start.sh" \
          "${KAFKA_DIR}/config/zookeeper.properties" > "${KAFKA_DIR}/logs/zookeeper.out" 2> \
          "${KAFKA_DIR}/logs/zookeeper.err" < /dev/null &
        ZOO_PID=$!
        sleep 10

        # We have more test cases in the image, but this is a simple quick-win to check if the service is running.
        # That's becasue Zookeeper stops printing logs after it prints the Banner on the CI, but works fine in the image and locally.
        grep "Starting server" "${KAFKA_DIR}/logs/zookeeper.out" > /dev/null || { cat "${KAFKA_DIR}/logs/zookeeper.out"; echo "Zookeeper log entry not found"; exit 1; }

        echo "Starting Kafka..."
        nohup "${KAFKA_DIR}/bin/kafka-server-start.sh" "${KAFKA_DIR}/config/server.properties" > "${KAFKA_DIR}/logs/kafka.out" 2> "${KAFKA_DIR}/logs/kafka.err" < /dev/null &
        KAFKA_PID=$!
        sleep 10

        # Kafka doesn't print logs on the CI, but works fine in the image test and locally.
        # grep "Controller 0 connected" "${KAFKA_DIR}/logs/controller.log" > /dev/null || { cat "${KAFKA_DIR}/logs/controller.log"; echo "Kafka log entry not found"; exit 1; }

        # Cleanup
        kill $KAFKA_PID
        kill $ZOO_PID
