package:
  name: elastic-dockerfiles
  version: 8.13.3
  epoch: 0
  description: Dockerfiles for the official Elastic Stack images
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4e109d7042669ade22f16643084c86c217b12ee0
      repository: https://github.com/elastic/dockerfiles
      tag: v${{package.version}}

data:
  - name: configs
    items:
      elasticsearch: elasticsearch
      kibana: kibana
      logstash: logstash

subpackages:
  - range: configs
    name: "${{package.name}}-${{range.key}}"
    pipeline:
      - runs: |
          mkdir -p ${{targets.destdir}}/usr/share/${{range.key}}/config
          cp -r ${{range.value}}/* ${{targets.destdir}}/usr/share/${{range.key}}/config
      - runs: |
          mkdir -p ${{targets.destdir}}/usr/share/${{range.key}}/bin
          cp -r bin/* ${{targets.destdir}}/usr/share/${{range.key}}/bin
          # Dockerfile(s) expects binaries in /usr/local/bin
          for file in ${{targets.destdir}}/usr/share/${{range.key}}/bin/*; do
            ln -s $file ${{targets.destdir}}/usr/local/bin/$(basename $file)
          done

update:
  enabled: true
  github:
    identifier: elastic/dockerfiles
    use-tag: true
    tag-filter: v
    strip-prefix: v
