package:
  name: iptables-wrapper
  version: 2
  epoch: 0
  description: Wrapper scripts for using iptables in containers
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - iptables

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - iptables

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/iptables-wrappers
      tag: v${{package.version}}
      expected-commit: e139a115350974aac8a82ec4b815d2845f86997e

  - runs: |
      # This script generates a wrapper based on the version
      # of iptables provided by the build environment.
      ./iptables-wrapper-installer.sh
      mkdir -p ${{targets.contextdir}}/sbin
      mkdir -p ${{targets.contextdir}}/usr/sbin
      mv /sbin/iptables-wrapper ${{targets.contextdir}}/sbin/iptables-wrapper
      ln -sf /sbin/iptables-wrapper ${{targets.contextdir}}/usr/sbin/iptables-wrapper

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by amazon-vpc-cni-k8s"
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - runs: |
          rm -rf ${{targets.contextdir}}/usr/sbin/iptables # Not needed for the compat package
          mkdir -p "${{targets.contextdir}}"/usr/sbin
          ln -sf /sbin/iptables-wrapper ${{targets.contextdir}}/usr/sbin/iptables

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/iptables-wrappers
    use-tag: true
    strip-prefix: v
