package:
  name: kafka_exporter
  version: 1.8.0
  epoch: 1
  description: "Kafka exporter for Prometheus"
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/danielqsj/kafka_exporter
      tag: v${{package.version}}
      expected-commit: 477643dd764c46ddd804ac4bd4022be877e3085b

  - uses: go/build
    with:
      packages: .
      output: kafka_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: danielqsj/kafka_exporter
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by upstream Dockerfile"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/opt/kafka-exporter
          # https://github.com/strimzi/strimzi-kafka-operator/blob/23c0fb0726e1f212c6182eb251ff23697e72a353/docker-images/kafka-based/kafka/Dockerfile#L33
          ln -sf /usr/bin/kafka_exporter ${{targets.contextdir}}/opt/kafka-exporter/kafka_exporter

test:
  pipeline:
    - runs: |
        kafka_exporter --version
