package:
  name: kibana
  version: 8.13.3
  epoch: 0
  description: Your window into the Elastic Stack
  copyright:
    - license: Apache-2.0
    - license: Elastic-2.0
  dependencies:
    runtime:
      - bash
      - curl
      - elastic-dockerfiles-kibana
      - font-liberation
      - font-noto-cjk
      - fontconfig
      - libfontconfig1
      - libnss
      - tini

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - make
      - yarn
      - nvm
      - maven

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/elastic/kibana
      tag: v${{package.version}}
      expected-commit: 003e4a42946390c2eb93dfb3586498ce7520a530

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/share/kibana
      chmod g+ws "${{targets.destdir}}"/usr/share/kibana

  - runs: |
      builddir=$(pwd)
      source /usr/share/nvm/nvm.sh
      nvm use
      yarn kbn bootstrap
      yarn start --run-examples

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    # https://github.com/elastic/dockerfiles/blob/4269a02cf8a56844db30e5e74b23087840ee6fcb/kibana/Dockerfile#L82C29-L82C40
    description: "Compatibility package to place binaries in the location expected by upstream Dockerfile"
    dependencies:
      runtime:
        - "${{package.name}}"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/opt
          ln -sf /usr/share/kibana ${{targets.contextdir}}/opt/kibana

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: elastic/kibana
