package:
  epoch: 1
  name: kubeflow-katib
  version: 0.15.0
  description: Kubeflow Katib services
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - build-base
      - python-3.10-dev
      - py3.10-pip
      - gfortran
      - pcre-dev

data:
  - name: go-builds
    items:
      cert-generator: cert-generator/v1beta1
      controller: katib-controller/v1beta1
      db-manager: db-manager/v1beta1
      file-metricscollector: metricscollector/v1beta1/file-metricscollector
      suggestion-goptuna: suggestion/goptuna/v1beta1

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubeflow/katib
      expected-commit: 05ab6f012ab6723609700a47a6cfa1845080e9b6
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: bump_requirements.patch

subpackages:
  - range: go-builds
    name: "katib-${{range.key}}"
    description: Kubeflow Katib ${{range.key}}
    pipeline:
      - uses: go/build
        with:
          packages: "./cmd/${{range.value}}"
          output: katib-${{range.key}}
          ldflags: -X main.version=${{package.version}}
          subpackage: true
          deps: golang.org/x/net@v0.7.0 github.com/docker/distribution@v2.8.2 github.com/docker/docker@v20.10.24

  - name: katib-earlystopping
    description: Kubeflow Katib earlystopping
    dependencies:
      runtime:
        - py3-grpcio
        - py3-protobuf
        - py3-googleapis-common-protos
        - py3-kubernetes
        - cython
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cd ./cmd/earlystopping/medianstop/v1beta1
          install -Dm755 ./main.py ${{targets.subpkgdir}}/usr/bin/

  - name: katib-tfevent-metricscollector
    description: Kubeflow Katib tfevent-metricscollector
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cd ./cmd/metricscollector/v1beta1/tfevent-metricscollector
          pip install --prefer-binary -r requirements.txt --prefix=/usr --root=${{targets.subpkgdir}}
          install -Dm755 ./main.py ${{targets.subpkgdir}}/usr/bin/

  - name: katib-suggestion-hyperband
    description: Kubeflow Katib suggestion-hyperband
    dependencies:
      runtime:
        - py3-grpcio
        - py3-cloudpickle
        - py3-numpy
        - py3-scikit-learn
        - py3-scipy
        - py3-forestci
        - py3-protobuf
        - py3-googleapis-common-protos
        - cython
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cd ./cmd/suggestion/hyperband/v1beta1
          install -Dm755 ./main.py ${{targets.subpkgdir}}/usr/bin/

  - name: katib-suggestion-hyperopt
    description: Kubeflow Katib suggestion-hyperopt
    dependencies:
      runtime:
        - py3-grpcio
        - py3-cloudpickle
        - py3-numpy
        - py3-scikit-learn
        - py3-scipy
        - py3-forestci
        - py3-protobuf
        - py3-googleapis-common-protos
        - cython
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cd ./cmd/suggestion/hyperopt/v1beta1
          install -Dm755 ./main.py ${{targets.subpkgdir}}/usr/bin/

  - name: katib-suggestion-nas-darts
    description: Kubeflow Katib suggestion-nas-darts
    dependencies:
      runtime:
        - py3-grpcio
        - py3-protobuf
        - py3-googleapis-common-protos
        - cython
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cd ./cmd/suggestion/nas/darts/v1beta1
          install -Dm755 ./main.py ${{targets.subpkgdir}}/usr/bin/

  - name: katib-suggestion-nas-enas
    description: Kubeflow Katib suggestion-nas-enas
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cd ./cmd/suggestion/nas/enas/v1beta1
          pip install --prefer-binary -r requirements.txt --prefix=/usr --root=${{targets.subpkgdir}}
          install -Dm755 ./main.py ${{targets.subpkgdir}}/usr/bin/

  - name: katib-suggestion-optuna-enas
    description: Kubeflow Katib suggestion-optuna-enas
    dependencies:
      runtime:
        - py3-grpcio
        - py3-protobuf
        - py3-googleapis-common-protos
        - py3-optuna
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cd ./cmd/suggestion/optuna/v1beta1
          install -Dm755 ./main.py ${{targets.subpkgdir}}/usr/bin/

  - name: katib-suggestion-pbt-enas
    description: Kubeflow Katib suggestion-pbt-enas
    dependencies:
      runtime:
        - py3-grpcio
        - py3-protobuf
        - py3-googleapis-common-protos
        - py3-numpy
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cd ./cmd/suggestion/pbt/v1beta1
          install -Dm755 ./main.py ${{targets.subpkgdir}}/usr/bin/

  - name: katib-suggestion-skopt-enas
    description: Kubeflow Katib suggestion-skopt-enas
    dependencies:
      runtime:
        - py3-grpcio
        - py3-cloudpickle
        - py3-numpy
        - py3-scikit-learn
        - py3-scikit-optimize
        - py3-scipy
        - py3-forestci
        - py3-protobuf
        - py3-googleapis-common-protos
        - cython
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cd ./cmd/suggestion/skopt/v1beta1
          install -Dm755 ./main.py ${{targets.subpkgdir}}/usr/bin/

update:
  enabled: true
  github:
    identifier: kubeflow/katib
    strip-prefix: v
    use-tag: true
