package:
  name: osixia-container-baseimage
  version: 1.3.3
  epoch: 0
  description: Required base packages and scripts for osixia/docker-openldap image
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - bash
      - cfssl
      - cfssl-json
      - glibc-locale-en
      - gnupg
      - gnupg-dirmngr
      - iproute2
      - logrotate
      - procps
      - py3-pyyaml
      - python3
      - runit

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

vars:
  # A common package name for this and osixia-docker-openldap packages.
  APP_NAME: osixia-openldap

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/osixia/container-baseimage
      tag: v${{package.version}}
      expected-commit: 8200d17647fac9390d9f3b5550a03be113a40f8c

  - uses: patch
    with:
      patches: 0001-fix-for-wolfi.patch

  - runs: |
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/service
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/run/state
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/run/environment
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/run/process
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/run/service
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/run/startup
      for dir in service-available tool; do
        mv ./image/${dir}/ "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/${dir}
      done
      # We bundle all the services in the image, so mark as "multiple_process_stack".
      touch "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/multiple_process_stack_added

  - runs: |
      mkdir -p "${{targets.contextdir}}"/usr/bin
      mkdir -p "${{targets.contextdir}}"/sbin
      for f in "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/tool/*; do
        # Skip 'run' binary, since it got conflict with the 'run' binary during melange build
        if [ "$(basename "$f")" = "run" ]; then
          continue
        fi
        filename=$(basename "$f")
        ln -sf /etc/${{vars.APP_NAME}}/container/tool/"$filename" "${{targets.contextdir}}"/usr/bin/"$filename"
      done
      ln -sf /etc/${{vars.APP_NAME}}/container/tool/run "${{targets.contextdir}}"/sbin/run

  - runs: |
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/environment
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/environment/startup
      printf en_US.UTF-8 > "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/environment/LANG
      printf en_US.UTF-8 > "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/environment/LANGUAGE
      printf en_US.UTF-8 > "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/environment/LC_CTYPE
      printf no > "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/environment/INITRD

  # https://github.com/osixia/container-baseimage/tree/main/image/service-available/%3Acron
  - runs: |
      mkdir -p "${{targets.contextdir}}"/etc/crontab
      mkdir -p "${{targets.contextdir}}"/etc/pam.d
      for dir in crontab cron.d cron.daily cron.hourly cron.monthly cron.weekly; do
        mkdir -p "${{targets.contextdir}}"/etc/$dir
        touch "${{targets.contextdir}}"/etc/$dir/.keep
      done

  # https://github.com/osixia/container-baseimage/tree/main/image/service-available/%3Alogrotate
  - runs: |
      mkdir -p "${{targets.contextdir}}"/etc/logrotate.d
      ln -sf /etc/${{vars.APP_NAME}}/container/service-available/:logrotate/assets/config/logrotate.conf "${{targets.contextdir}}"/etc/logrotate.conf
      ln -sf /etc/${{vars.APP_NAME}}/container/service-available/:logrotate/assets/config/logrotate_syslogng "${{targets.contextdir}}"/etc/logrotate.d/syslog-ng

  # https://github.com/osixia/container-baseimage/tree/main/image/service-available/%3Assl-tools
  - runs: |
      chmod 700 "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/service-available/:ssl-tools/assets/tool/*
      for f in "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/service-available/:ssl-tools/assets/tool/*; do
        filename=$(basename "$f")
        ln -sf /etc/${{vars.APP_NAME}}/container/service-available/:ssl-tools/assets/tool/"$filename" "${{targets.contextdir}}"/usr/bin/"$filename"
      done

  # https://github.com/osixia/container-baseimage/tree/main/image/service-available/%3Asyslog-ng-core
  - runs: |
      mkdir -p "${{targets.contextdir}}"/etc/default
      mkdir -p "${{targets.contextdir}}"/etc/syslog-ng
      ln -sf /etc/${{vars.APP_NAME}}/container/service-available/:syslog-ng-core/assets/config/syslog_ng_default "${{targets.contextdir}}"/etc/default/syslog-ng
      ln -sf /etc/${{vars.APP_NAME}}/container/service-available/:syslog-ng-core/assets/config/syslog-ng.conf "${{targets.contextdir}}"/etc/syslog-ng/syslog-ng.conf

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream image"
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}/container"
          ln -sf /etc/${{vars.APP_NAME}}/container/service-available "${{targets.contextdir}}"/container/service-available
          ln -sf /etc/${{vars.APP_NAME}}/container/tool "${{targets.contextdir}}"/container/tool

          mkdir -p "${{targets.contextdir}}"/usr/bin
          mkdir -p "${{targets.contextdir}}"/sbin

          # https://github.com/osixia/container-baseimage/blob/761451de259b7e16c9a4664c8ea3cb476b6425c6/image/build.sh#L29-L32
          ln -sf /usr/bin/true "${{targets.contextdir}}"/sbin/initctl
          ln -sf /usr/bin/true "${{targets.contextdir}}"/usr/bin/initctl

          # https://github.com/osixia/container-baseimage/blob/761451de259b7e16c9a4664c8ea3cb476b6425c6/image/build.sh#L34-L39
          ln -sf /usr/bin/true "${{targets.contextdir}}"/sbin/ischroot
          ln -sf /usr/bin/true "${{targets.contextdir}}"/usr/bin/ischroot

update:
  enabled: true
  ignore-regex-patterns:
    - alpine-
    - jessie-
    - ubuntu-
  github:
    identifier: osixia/container-baseimage
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
  pipeline:
    - runs: /container/tool/run --loglevel=trace --no-kill-all-on-exit
    - runs: log-helper info hello | grep -i hello
    - runs: setuser root true
    - runs: complex-bash-env true
    - runs: add-service-available :runit :syslog-ng-core :logrotate :cron
