package:
  name: osixia-container-baseimage
  version: 1.3.3
  epoch: 0
  description: Required base packages and scripts for osixia/docker-openldap image
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - glibc-locale-en

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/osixia/container-baseimage
      tag: v${{package.version}}
      expected-commit: 8200d17647fac9390d9f3b5550a03be113a40f8c

  - runs: |
      mkdir -p "${{targets.contextdir}}"/etc/${{package.name}}/container
      for dir in service-available tool; do
        mv ./${dir}/ "${{targets.contextdir}}"/etc/${{package.name}}/container/${dir}
      done

  - runs: |
      mkdir -p "${{targets.contextdir}}"/etc/${{package.name}}/container/environment
      printf en_US.UTF-8 > "${{targets.contextdir}}"/etc/${{package.name}}/container/environment/LANG
      printf en_US.UTF-8 > "${{targets.contextdir}}"/etc/${{package.name}}/container/environment/LANGUAGE
      printf en_US.UTF-8 > "${{targets.contextdir}}"/etc/${{package.name}}/container/environment/LC_CTYPE

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream image"
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}/container"
          ln -sf /etc/${{package.name}}/container/service "${{targets.contextdir}}/container/service"
          ln -sf /etc/${{package.name}}/container/environment "${{targets.contextdir}}/container/environment"

update:
  enabled: true
  github:
    identifier: osixia/container-baseimage
    strip-prefix: v
