package:
  name: osixia-docker-openldap
  version: 1.5.0
  epoch: 0
  description: Required packages and scripts for osixia/docker-openldap image
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - bash
      - openldap
      - openldap-backend-all
      - osixia-container-baseimage-compat

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - osixia-container-baseimage
      - python3

vars:
  # A common package name for this and osixia-container-baseimage packages.
  APP_NAME: osixia-openldap

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/osixia/docker-openldap
      tag: v${{package.version}}
      expected-commit: 32eb22ce1e9b34e893d97acf6c6cd7c6fea787ab

  - runs: |
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/service
      mkdir -p "${{targets.contextdir}}"/etc/${{vars.APP_NAME}}/container/environment

  - working-directory: image
    pipeline:
      - runs: |
          # Alpine equivalent of usermod is adduser
          sed -i 's|usermod -o -u "$LDAP_OPENLDAP_UID" openldap|adduser -u "$LDAP_OPENLDAP_UID" -D openldap|' ./service/slapd/startup.sh
          sed -i 's|groupmod -o -g "$LDAP_OPENLDAP_GID" openldap|addgroup -g "$LDAP_OPENLDAP_GID" openldap|' ./service/slapd/startup.sh
      - runs: |
          mv ./service/ ${{targets.contextdir}}/etc/${{vars.APP_NAME}}/container
          mv ./environment/ ${{targets.contextdir}}/etc/${{vars.APP_NAME}}/container/environment/99-default
      - runs: |
          # https://github.com/osixia/docker-openldap/blob/635034a75878773f8576d646422cf26e43741fab/image/Dockerfile#L54C5-L54C36
          /etc/${{vars.APP_NAME}}/container/tool/install-service

  - runs: |
      ${{targets.contextdir}}/etc/${{vars.APP_NAME}}/container/service/slapd/startup.sh

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream image"
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}/container"
          ln -sf /etc/${{vars.APP_NAME}}/container/service "${{targets.contextdir}}/container/service"
          ln -sf /etc/${{vars.APP_NAME}}/container/environment "${{targets.contextdir}}/container/environment"

update:
  enabled: true
  github:
    identifier: osixia/docker-openldap
    strip-prefix: v
