package:
  name: percona-xtrabackup-8.4
  version: 8.4.0
  epoch: 0
  description: Open source hot backup tool for InnoDB and XtraDB databases
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - bison
      - bpftool
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates
      - clang-18
      - clang-18-dev
      - clang-18-extras
      - cmake
      - curl
      - curl-dev
      - elfutils-dev
      - vim
      - eudev-dev
      - gcc-12-default
      - git
      - grpc-dev
      - hardening-check
      - isl-dev
      - libaio-dev
      - libbpf
      - libbpf-dev
      - libcurl-openssl4
      - libelf-static
      - libev-dev
      - libgcrypt-dev
      - liblz4-1
      - libtool
      - lsb-release-minimal
      - lz4
      - lz4-dev
      - mpc-dev
      - ncurses-dev
      # - libdbd-mysql-perl
      - numactl-dev
      - openssl-dev
      - pkgconf
      - procps-dev
      - protobuf-dev
      - py3-docutils
      # - qpress
      - py3-sphinx
      - rsync
      - socat
      - rtmpdump-dev
      - librtmp
      - yaml-cpp-dev
      - zlib-dev
      - zstd

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/percona/percona-xtrabackup
      tag: percona-xtrabackup-${{package.version}}
      expected-commit: da6e1abde099d91b9b725f44b944f95db156cf7f
      recurse-submodules: true

  - runs: |
      mkdir build && cd build
      cmake \
        -DWITH_BOOST=PATH-TO-BOOST-LIBRARY \
        -DDOWNLOAD_BOOST=ON \
        -DBUILD_CONFIG=xtrabackup_release \
        -DWITH_MAN_PAGES=OFF \
        ..
      make -j$(nproc)

  - working-directory: build
    uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/local/xtrabackup/bin/
          ln -sf /usr/bin/xtrabackup ${{targets.contextdir}}/usr/local/xtrabackup/bin/xtrabackup

update:
  enabled: true
  github:
    identifier: percona/percona-xtrabackup
    strip-prefix: percona-xtrabackup-
    use-tag: true
    tag-filter: percona-xtrabackup-8.4
