package:
  name: percona-server-8.4
  version: 8.4.0
  epoch: 0
  description: "Percona Server for MySQL is a free, fully compatible, enhanced, and open source drop-in replacement for any MySQL database. It provides superior performance, scalability, and instrumentation."
  copyright:
    # TODO: The "extra" directory contains a lot of licenses called "COPYING" or "LICENSE".
    # We should add them here but the folders are versioned and dynamically changing per
    # release. We need to find a way to include them all in the SBOM, rather than just
    # copying the files under the /usr/share/percona-server/licenses directory.
    - license: GPL-3.0-or-later
    - license: BSD-3-Clause
  dependencies:
    provides:
      - percona-server=${{package.full-version}}

# Replace the last `.` with `-` to fetch the correct tag.
var-transforms:
  - from: ${{package.version}}
    match: '\.(\d+)$'
    replace: "-$1"
    to: mangled-package-version

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-extras
      - cmake
      - curl-dev
      - libaio-dev
      - libedit
      - libevent-dev
      - libtirpc-dev
      - linux-pam-dev
      - ncurses-dev
      - nfs-utils
      - openldap-dev
      - openssl-dev
      - pcre2-dev
      - perl
      - readline-dev
      - rpcgen
      - samurai
      - sed
      - wolfi-baselayout
      - xz-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/percona/percona-server
      tag: Percona-Server-${{package.version}}-1
      expected-commit: 238b3c022afec1fc0a2fbffda77cb35cc3697b26
      recurse-submodules: true

  - name: "Remove Coredumper Support"
    runs: |
      sed -i 's/INCLUDE(coredumper)//g' CMakeLists.txt
      sed -i 's/MYSQL_CHECK_COREDUMPER()//g' CMakeLists.txt
      sed -i 's/OPTION (WITH_COREDUMPER "Enable support for coredumper library" ON)//g' CMakeLists.txt

  - name: "Cmake"
    runs: |
      mkdir /var/tmp
      cmake . -G Ninja \
        -DFORCE_INSOURCE_BUILD=1 \
        -DBUILD_CONFIG=mysql_release \
        -DWITH_EDITLINE=system \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DSYSCONFDIR=/etc \
        -DMYSQL_DATADIR=/var/lib/mysql \
        -DMYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock \
        -DDEFAULT_CHARSET=utf8mb4 \
        -DDEFAULT_COLLATION=utf8mb4_general_ci \
        -DENABLED_LOCAL_INFILE=ON \
        -DINSTALL_INFODIR=share/info \
        -DINSTALL_MANDIR=share/man \
        -DINSTALL_PLUGINDIR=lib/${{package.name}}/plugin \
        -DINSTALL_INCLUDEDIR=include/mysql \
        -DINSTALL_DOCREADMEDIR=share/doc/${{package.name}} \
        -DINSTALL_SUPPORTFILESDIR=share/${{package.name}} \
        -DINSTALL_DOCDIR=share/doc/${{package.name}} \
        -DWITH_ROCKSDB=NO \
        -DTMPDIR=/var/tmp \
        -DWITH_ASAN=OFF \
        -DWITH_EXTRA_CHARSETS=complex \
        -DWITH_SYSTEMD=no \
        -DWITH_SSL=system \
        -DWITH_VALGRIND=OFF \
        -DWITH_ZLIB=system \

  - name: "Install"
    runs: |
      DESTDIR="${{targets.destdir}}" ninja install

  - name: "Remove extras"
    runs: |
      rm -rf "${{targets.destdir}}"/usr/mysql-test
      rm -rf "${{targets.destdir}}"/usr/lib/libmysqlclient.so
      rm -rf "${{targets.destdir}}"/usr/lib/libmysqlclient_r.so

  - name: "Create required data directories"
    runs: |
      mkdir -p "${{targets.destdir}}"/run/mysqld
      mkdir -p "${{targets.destdir}}"/var/lib/mysql
      mkdir -p "${{targets.destdir}}"/var/tmp

subpackages:
  - name: "${{package.name}}-dev"
    description: "headers for percona-server"
    pipeline:
      - uses: split/dev

  - name: ${{package.name}}-oci-entrypoint
    description: Entrypoint for percona-server in OCI containers
    dependencies:
      runtime:
        - bash
        - busybox
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cp docker-entrypoint.sh ${{targets.subpkgdir}}/usr/bin/
          chmod +x ${{targets.subpkgdir}}/usr/bin/docker-entrypoint.sh

  - name: ${{package.name}}-oci-entrypoint-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p "${{targets.subpkgdir}}"
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -sf /usr/bin/docker-entrypoint.sh ${{targets.subpkgdir}}/entrypoint.sh
          ln -sf /usr/bin/docker-entrypoint.sh ${{targets.subpkgdir}}/usr/local/bin/docker-entrypoint.sh
    dependencies:
      runtime:
        - ${{package.name}}-oci-entrypoint

update:
  enabled: true
  github:
    identifier: percona/percona-server
    tag-filter: Percona-Server-8.4.
    strip-prefix: Percona-Server-
    use-tag: true
  version-transform:
    - match: ^(.+)\-(\d+)$
      replace: $1.$2

test:
  pipeline:
    - runs: |
        mysqld --initialize
