package:
  name: py3-idna
  version: 3.4
  epoch: 0
  description: "IDNA 2008 and UTS #46 for Python3"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3
      - py3-asn1

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools
      - py3-gpep517
      - py3-flit-core
      - py3-installer
      - py3-wheel

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/kjd/idna/archive/v${{package.version}}.tar.gz
      expected-sha256: afbfa0caebd4872b38ab1af86b37bd4f46d4fccc8d5ce226cb9ee91b91196848

  - runs: |
      gpep517 build-wheel --wheel-dir .dist --output-fd 3 3>&1 >&2

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/idna-${{package.version}}-py3-none-any.whl

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 5487
