package:
  name: py3-tfx-bsl
  version: 1.14.0
  epoch: 0
  description: Common code for TFX
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-absl-py
      - py3-apache-beam
      - py3-google-api-python-client
      - numpy
      - py3-pandas
      - py3-protobuf
      - pyarrow
      - tensorflow-core
      - py3-tensorflow-core
      - py3-tensorflow-metadata
      - py3-tensorflow-serving-api
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - python-3-dev
      - py3-setuptools
      - py3-pip
      - py3-wheel
      - numpy
      - bazel-6
      - openjdk-17
      - openjdk-17-jre
      - bash
      - patch
      - m4
      - py3-six
      - py3-absl-py
      - py3-gpep517
      - py3-installer
      - apache-arrow
      - apache-arrow-dev
      - abseil-cpp
      - protobuf
      - py3-tensorflow-metadata
      - tensorflow-core
      - py3-pybind11
      - py3-pybind11-dev
      - py3-pyfarmhash
      - zetasql-dev
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tensorflow/tfx-bsl
      expected-commit: 98fe47e2368463565f95380048839d8c6ac8a682
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: 0001-bump-six-to-1.16-and-m4-1.4.19.patch

  - runs: |
      # `distutils` is deprecated in Python 3.12, so we need to use `setuptools` instead.
      sed -i -e 's/from distutils.command import build/from setuptools.command import build/g' setup.py

  - runs: |
      python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 1
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl
      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +

  - uses: strip

update:
  enabled: true
  github:
    identifier: tensorflow/tfx-bsl
    strip-prefix: v
