package:
  name: py3-tfx-bsl
  version: 1.14.0
  epoch: 0
  description: Common code for TFX
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-absl-py
      - py3-apache-beam
      - py3-google-api-python-client
      - numpy
      - py3-pandas
      - py3-protobuf
      - pyarrow
      - tensorflow-core
      - py3-tensorflow-core
      - py3-tensorflow-metadata
      - py3-tensorflow-serving-api

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3.10
      - py3.10-setuptools
      - py3.10-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tensorflow/tfx-bsl
      expected-commit: 98fe47e2368463565f95380048839d8c6ac8a682
      tag: v${{package.version}}

  - name: Download tfx-bsl from PyPI
    runs: |
      # FIXME: This is a hack to get around the fact that tfx-bsl is not
      # get built as a wheel on Wolfi due to a bug in their BAZEL build
      # system. See: https://github.com/wolfi-dev/os/pull/7199
      # `tfx-bsl` also does not support >= Python 3.11.
      pip install tfx-bsl --no-deps --ignore-requires-python --prefix=/usr --root=${{targets.destdir}} -i https://pypi.org/simple/ --extra-index-url https://pypi-nightly.tensorflow.org/simple

  - uses: strip

update:
  enabled: true
  github:
    identifier: tensorflow/tfx-bsl
    strip-prefix: v
