package:
  name: py3-requests
  version: 2.31.0
  epoch: 0
  description: "HTTP request library for Python3"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - py3-certifi
      - py3-charset-normalizer
      - py3-idna
      - py3-urllib3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-gpep517
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/r/requests/requests-${{package.version}}.tar.gz
      expected-sha256: 942c5a758f98d790eaed1a29cb6eefc7ffb0d1cf7af05c3d2791656dbd6ad1e1

  - runs: |
      gpep517 build-wheel --wheel-dir .dist --output-fd 3 3>&1 >&2

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/requests-*.whl

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 4004
